# 1. Permanent Port for Grafana UI
grafana:
  service:
    type: NodePort
    nodePort: 30000

# 2. Prometheus Configuration
prometheus:
  # This exposes the Prometheus UI on a permanent port
  service:
    type: NodePort
    nodePort: 30090

  prometheusSpec:
    # Your Bot Scraping Logic
    additionalScrapeConfigs:
      - job_name: 'job-bot-business-metrics'
        ec2_sd_configs:
          - region: eu-central-1
            port: 80
            filters:
              - name: tag:aws:autoscaling:groupName
                values:
                  - job-bot-asg
      - job_name: 'job-bot-hardware-metrics'
        ec2_sd_configs:
          - region: eu-central-1
            port: 9100
            filters:
              - name: tag:aws:autoscaling:groupName
                values:
                  - job-bot-asg