replicas: 1
minimumMasterNodes: 1
esJavaOpts: "-Xmx1g -Xms1g"

# Tell the readiness probe to accept a 1-node "yellow" cluster
clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

resources:
  requests:
    cpu: "200m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "local-path"
  resources:
    requests:
      storage: 5Gi

antiAffinity: "soft"