service:
  type: NodePort
  ports:
    - name: beats
      port: 5044
      targetPort: 5044
      nodePort: 30092 
      protocol: TCP

# Mount the password into the pod as a file
secretMounts:
  - name: elasticsearch-master-credentials
    secretName: elasticsearch-master-credentials
    path: /usr/share/logstash/config/certs

logstashConfig:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.hosts: [ "https://elasticsearch-master:9200" ]
    xpack.monitoring.elasticsearch.username: "elastic"
    xpack.monitoring.elasticsearch.password: "${cat /usr/share/logstash/config/certs/password}"
    xpack.monitoring.elasticsearch.ssl.verification_mode: none

logstashPipeline:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    output {
      elasticsearch {
        hosts => ["https://elasticsearch-master:9200"]
        user => "elastic"
        password => "${cat /usr/share/logstash/config/certs/password}"
        ssl_certificate_verification => false
        index => "bot-logs-%{+YYYY.MM.dd}"
      }
    }