name: Deploy Dispatcher to Lambda

on:
  push:
    branches: [ "main" ]
    paths: [ "dispatcher/**", "shared/**" , ".github/workflows/deploy-dispatcher.yml"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Zip and Update Lambda
        run: |
          mkdir -p lambda_package
          cp dispatcher/main.py lambda_package/
          cp -r shared lambda_package/
          cd lambda_package
          zip -r ../deployment.zip .
          cd ..
          aws lambda update-function-code \
            --region eu-central-1 \
            --function-name linkedin-dispatcher-function \
            --zip-file fileb://deployment.zip